apiVersion: v2
name: coredns-crd
version: 1.45.0
appVersion: 1.13.1
home: https://coredns.io
icon: https://coredns.io/images/CoreDNS_Colour_Horizontal.png
description: Additional CoreDNS deployment with k8s_crd plugin for handling DNSEndpoints
keywords:
  - coredns
  - dns
  - kubedns
sources:
  - https://github.com/coredns/coredns
maintainers:
  - name: mrueg
  - name: haad
  - name: hagaibarel
  - name: shubham-cmyk
type: application
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump to CoreDNS 1.13.1
